"""Adversarial attacks from paper Table 8 (§5.4): 10 attacks × 6 variants.

Surfaces and attacks:
  URL:   A1 Shortener, A2 Combosquat, A3 TLD Substitution
  HTML:  A4 Invisible Link, A5 Object Ratio, A6 DOM Expand, A7 Input Obfuscate
  Logo:  A8 Masking, A9 Manipulation, A10 Font Substitution

60 single-surface configs plus 4 combo scenarios (URL+HTML, URL+Logo,
HTML+Logo, URL+HTML+Logo) generated by :mod:`evasion.generate_combos`.

Each attack class exposes :meth:`get_variants` (returning six variant
names ``v1..v6``) and :meth:`apply` which reads the clean feature cache
for a URL and writes the perturbed equivalent under an output dir.
"""

# URL and HTML attacks depend only on the Python stdlib + bs4, so they
# load eagerly. Logo attacks pull in cv2 / Pillow; load them lazily so
# someone scoring only the URL or HTML surface on a machine without
# OpenCV doesn't get an ImportError at module-import time.
from .a1_url_shortener import A1UrlShortener
from .a2_url_combosquat import A2UrlCombosquat
from .a3_url_tld_sub import A3UrlTldSub
from .a4_html_invisible_link import A4HtmlInvisibleLink
from .a5_html_object_ratio import A5HtmlObjectRatio
from .a6_html_dom_expand import A6HtmlDomExpand
from .a7_html_input_obfuscate import A7HtmlInputObfuscate


def _lazy_logo_attacks():
    """Import logo attacks on first use. Requires cv2 + Pillow."""
    from .a8_logo_masking import A8LogoMasking
    from .a9_logo_manipulation import A9LogoManipulation
    from .a10_logo_font_subst import A10LogoFontSubst
    return {
        "A8_logo_masking": A8LogoMasking,
        "A9_logo_manipulation": A9LogoManipulation,
        "A10_logo_font_subst": A10LogoFontSubst,
    }


class _LazyLogoProxy:
    """Mapping proxy: deferred cv2/PIL import until a logo attack is read."""

    _ATTACKS_EAGER = {
        "A1_url_shortener": A1UrlShortener,
        "A2_url_combosquat": A2UrlCombosquat,
        "A3_url_tld_sub": A3UrlTldSub,
        "A4_html_invisible_link": A4HtmlInvisibleLink,
        "A5_html_object_ratio": A5HtmlObjectRatio,
        "A6_html_dom_expand": A6HtmlDomExpand,
        "A7_html_input_obfuscate": A7HtmlInputObfuscate,
    }
    _ATTACKS_LAZY_KEYS = (
        "A8_logo_masking", "A9_logo_manipulation", "A10_logo_font_subst"
    )

    def __init__(self):
        self._logo_cache = None

    def _logo(self):
        if self._logo_cache is None:
            self._logo_cache = _lazy_logo_attacks()
        return self._logo_cache

    def __getitem__(self, key):
        if key in self._ATTACKS_EAGER:
            return self._ATTACKS_EAGER[key]
        if key in self._ATTACKS_LAZY_KEYS:
            return self._logo()[key]
        raise KeyError(key)

    def __iter__(self):
        return iter(list(self._ATTACKS_EAGER) + list(self._ATTACKS_LAZY_KEYS))

    def __len__(self):
        return len(self._ATTACKS_EAGER) + len(self._ATTACKS_LAZY_KEYS)

    def keys(self):
        return list(self._ATTACKS_EAGER) + list(self._ATTACKS_LAZY_KEYS)

    def items(self):
        return [(k, self[k]) for k in self.keys()]

    def values(self):
        return [self[k] for k in self.keys()]

    def __contains__(self, key):
        return key in self._ATTACKS_EAGER or key in self._ATTACKS_LAZY_KEYS


ATTACKS = _LazyLogoProxy()

SURFACE_OF = {
    "A1_url_shortener": "url", "A2_url_combosquat": "url", "A3_url_tld_sub": "url",
    "A4_html_invisible_link": "html", "A5_html_object_ratio": "html",
    "A6_html_dom_expand": "html", "A7_html_input_obfuscate": "html",
    "A8_logo_masking": "logo", "A9_logo_manipulation": "logo", "A10_logo_font_subst": "logo",
}

ATTACKS_BY_SURFACE = {
    "url": ["A1_url_shortener", "A2_url_combosquat", "A3_url_tld_sub"],
    "html": ["A4_html_invisible_link", "A5_html_object_ratio", "A6_html_dom_expand", "A7_html_input_obfuscate"],
    "logo": ["A8_logo_masking", "A9_logo_manipulation", "A10_logo_font_subst"],
}
